### ISSUE TITLE
[Bug] Docs's EventMesh Java SDK in Maven can not be find.

### ISSUE THREAD

**Issue by scwlkq** [apache/eventmesh-site#192]
![image](https://github.com/apache/eventmesh-site/assets/89067331/d0180ccd-4946-4729-808f-8fb034520064)
![image](https://github.com/apache/eventmesh-site/assets/89067331/969d495d-c93c-40a6-8854-cecea0bf3daa)

**Comment by Pil0tXia** [comment]
Version tag should be `1.10.0-release`.
