### ISSUE TITLE
[Bug] Line endings of shell scripts are still CRLF and need conversion

### ISSUE THREAD

**Issue by arebya** [apache/eventmesh-site#197]
Event Runtime 快速开始需要修改start.sh/stop.sh 为unix格式，否则在mac下报错无法直接执行

**Comment by Pil0tXia** [comment]
May I ask that which EventMesh release are you using? This bug has been fixed in 1.10.0.

**Comment by arebya** [comment]
> May I ask that which EventMesh release are you using? This bug has been fixed in 1.10.0.

1.10.0
