### ISSUE TITLE
[Doc] The logo file in the lower left corner of the page is 404

### ISSUE THREAD

**Issue by Createsequence** [apache/eventmesh-site#229]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/eventmesh/issues?q=is%3Aissue) and found no similar issues.

### Documentation Related

I found that the logo file in the lower left corner of the page is not loaded correctly：

<img width="1491" alt="image" src="https://github.com/apache/eventmesh/assets/49221670/b6e4c1e6-9f60-4767-801e-be4cf39b2af0">

After opening the browser console, I found that the file is 404：

<img width="507" alt="image" src="https://github.com/apache/eventmesh/assets/49221670/d0f68f7d-26ab-411b-9957-c1bb0bec492e">

Was this file renamed or moved to another directory? I thought I might be able to try to fix this. :)

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct) *

**Comment by Pil0tXia** [comment]
@Createsequence I've transferred this issue to eventmesh-site repo. You may submit a PR and link that PR to this issue.
